// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQo1obDEq8c4LlBOOxiuUT_elKV2C8VFk',
    appId: '1:136133203472:web:a09d0f9c35f102b5a75c95',
    messagingSenderId: '136133203472',
    projectId: 'primeservices-b1870',
    authDomain: 'primeservices-b1870.firebaseapp.com',
    storageBucket: 'primeservices-b1870.appspot.com',
    measurementId: 'G-HL7DTEDRQS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXTRjigE-QelkKuo9qGsaOrdIR4MJiEdk',
    appId: '1:136133203472:android:c2a48b07f7af7dc2a75c95',
    messagingSenderId: '136133203472',
    projectId: 'primeservices-b1870',
    storageBucket: 'primeservices-b1870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjE8IIRvQQYkEpQp3zFZbYinnp2-jTIIs',
    appId: '1:136133203472:ios:3f5ffb3ce2b04f29a75c95',
    messagingSenderId: '136133203472',
    projectId: 'primeservices-b1870',
    storageBucket: 'primeservices-b1870.appspot.com',
    androidClientId: '136133203472-pdn7icd50ndmd0tedqi4me1i30euvq3e.apps.googleusercontent.com',
    iosClientId: '136133203472-s3635r5f9cupbhplee0utjmp28bdlri7.apps.googleusercontent.com',
    iosBundleId: 'com.example.primecabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjE8IIRvQQYkEpQp3zFZbYinnp2-jTIIs',
    appId: '1:136133203472:ios:3f5ffb3ce2b04f29a75c95',
    messagingSenderId: '136133203472',
    projectId: 'primeservices-b1870',
    storageBucket: 'primeservices-b1870.appspot.com',
    androidClientId: '136133203472-pdn7icd50ndmd0tedqi4me1i30euvq3e.apps.googleusercontent.com',
    iosClientId: '136133203472-s3635r5f9cupbhplee0utjmp28bdlri7.apps.googleusercontent.com',
    iosBundleId: 'com.example.primecabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQo1obDEq8c4LlBOOxiuUT_elKV2C8VFk',
    appId: '1:136133203472:web:9cf1b63461521132a75c95',
    messagingSenderId: '136133203472',
    projectId: 'primeservices-b1870',
    authDomain: 'primeservices-b1870.firebaseapp.com',
    storageBucket: 'primeservices-b1870.appspot.com',
    measurementId: 'G-F4TVTL5DBV',
  );

}