// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALO4wWuIU6YbXIoo_xV3h59q8x4OnpYKM',
    appId: '1:917975444880:web:63deb2b6ff2bbe2d519715',
    messagingSenderId: '917975444880',
    projectId: 'primecabs-eb17a',
    authDomain: 'primecabs-eb17a.firebaseapp.com',
    storageBucket: 'primecabs-eb17a.appspot.com',
    measurementId: 'G-HZFD7HQ8XM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0-QOIOAm2KaPoncjEAvlZDmP8a4OkVjY',
    appId: '1:917975444880:android:c24c55ba0068ea42519715',
    messagingSenderId: '917975444880',
    projectId: 'primecabs-eb17a',
    storageBucket: 'primecabs-eb17a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLv4LpQQFo1XCwakWGU2wZ3_zK92HWsSo',
    appId: '1:917975444880:ios:fa72ac7dbe5b7be3519715',
    messagingSenderId: '917975444880',
    projectId: 'primecabs-eb17a',
    storageBucket: 'primecabs-eb17a.appspot.com',
    iosBundleId: 'com.example.primecabs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLv4LpQQFo1XCwakWGU2wZ3_zK92HWsSo',
    appId: '1:917975444880:ios:fa72ac7dbe5b7be3519715',
    messagingSenderId: '917975444880',
    projectId: 'primecabs-eb17a',
    storageBucket: 'primecabs-eb17a.appspot.com',
    iosBundleId: 'com.example.primecabs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALO4wWuIU6YbXIoo_xV3h59q8x4OnpYKM',
    appId: '1:917975444880:web:c426b5c59ca721c1519715',
    messagingSenderId: '917975444880',
    projectId: 'primecabs-eb17a',
    authDomain: 'primecabs-eb17a.firebaseapp.com',
    storageBucket: 'primecabs-eb17a.appspot.com',
    measurementId: 'G-XJ9MDWESD4',
  );
}
